<a href="https://colab.research.google.com/github/LuizFelipeCavalcante/Nutrition-and-Depression/blob/main/src/AnaliseDepresao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Importação e pre limpeza
  Importei a base, selecionei apenas pessoas com depressão e pessoas sem nenhuma doença, filtrei pela idade de 18 a 29 anos.
  
  Salvei tudo na df_analise.csv

## Importação e pre limpeza

In [49]:
df = df_analise = pd.read_csv(
    r"/content/drive/MyDrive/PNS2019/pns2019.csv",
    sep=",",
    low_memory=False
)

KeyboardInterrupt:

In [ ]:
# Limpar nomes de colunas (evita erro escondido)
df.columns = df.columns.str.strip()

# # Renomear coluna
# df = df.rename(columns={"Q092": "depressao"})

# Filtrar idade 18 a 29 anos
df_idade = df[(df["C008"] > 17) & (df["C008"] < 30)]

# Quantidade com depressão
qtd_depressao = df_idade[df_idade["Q092"] == 1].shape[0]

# Quantidade sem nenhuma doença
qtd_sem_doencas = df_idade.query(
    "Q00201 == 2 and Q03001 == 2 and Q060 == 2 and Q06306 == 2 and "
    "Q068 == 2 and Q074 == 2 and Q079 == 2 and Q088 == 2 and "
    "Q11604 == 2 and Q120 == 2 and Q124 == 2 and Q128 == 2 and "
    "Q092 == 2 and Q084 == 2 and Q11006 == 2"
).shape[0]

total = qtd_depressao + qtd_sem_doencas

print("Total analisado:", total)
print("Com depressão:", qtd_depressao)
print("Sem nenhuma doença:", qtd_sem_doencas)

# Função para mostrar percentual + valor absoluto
def autopct_format(pct):
    valor = int(round(pct * total / 100.0))
    return f"{pct:.1f}%\n({valor})"

In [ ]:
# Filtrar grupos
df_com_dep = df_idade[df_idade["Q092"] == 1].copy()

df_sem_doenca = df_idade.query(
    "Q00201 == 2 and Q03001 == 2 and Q060 == 2 and Q06306 == 2 and "
    "Q068 == 2 and Q074 == 2 and Q079 == 2 and Q088 == 2 and "
    "Q11604 == 2 and Q120 == 2 and Q124 == 2 and Q128 == 2 and "
    "Q092 == 2 and Q084 == 2 and Q11006 == 2"
).copy()

# Adicionar label
df_com_dep["target"] = 1
df_sem_doenca["target"] = 0

# Unir e resetar index
df_analise = pd.concat([df_com_dep, df_sem_doenca], ignore_index=True)

print(f"Com depressão:     {df_com_dep.shape[0]}")
print(f"Sem doenças:       {df_sem_doenca.shape[0]}")
print(f"Total na base:     {df_base.shape[0]}")

In [ ]:
df_analise.head()

### Criação da base limpa

In [ ]:
# Base final de análise
df_analise.to_csv("/content/drive/MyDrive/PNS2019/df_analise.csv", index=False)

# Analise exploratoria

In [41]:
df = df_analise = pd.read_csv(
    r"/content/drive/MyDrive/PNS2019/df_analise.csv",
    sep=",",
    low_memory=False
)

## Analise Inicial

In [ ]:
display(df_analise.head())

In [ ]:
# @title
# Gráfico
qtd_depressao = df_analise[(df_analise['target'] == 1)].shape[0]
qtd_sem_doencas = df_analise[(df_analise['target'] == 0)].shape[0]
plt.figure()
plt.pie(
    [qtd_depressao, qtd_sem_doencas],
    labels=["Com depressão", "Sem nenhuma doença"],

)
plt.title("Depressão vs Nenhuma Doença (18–29 anos)")
plt.show()

### Casos por estado e regiao

In [ ]:
depressao_v0001 = df_analise[df_analise['Q092'] == 1]['V0001'].value_counts().sort_values(ascending=True)

# Create a mapping for V0001 values to state names
state_mapping = {
    11: 'RO',
    12: 'AC',
    13: 'AM',
    14: 'RR',
    15: 'PA',
    16: 'AP',
    17: 'TO',
    21: 'MA',
    22: 'PI',
    23: 'CE',
    24: 'RN',
    25: 'PB',
    26: 'PE',
    27: 'AL',
    28: 'SE',
    29: 'BA',
    31: 'MG',
    32: 'ES',
    33: 'RJ',
    35: 'SP',
    41: 'PR',
    42: 'SC',
    43: 'RS',
    50: 'MS',
    51: 'MT',
    52: 'GO',
    53: 'DF'
}

# Apply the mapping to the index of the series
depressao_v0001.index = depressao_v0001.index.map(state_mapping)

plt.figure(figsize=(10, 8)) # Increased figure size to accommodate more bars
depressao_v0001.plot(kind='barh')
plt.title('Distribuição de Estado para Pessoas com Depressão') # Removed 'Top 10'
plt.xlabel('Contagem')
plt.ylabel('Estado')
plt.grid(axis='x', linestyle='--')
plt.tight_layout()
plt.show()

print(f"Total de casos de depressão nos estados mapeados: {depressao_v0001.sum()}/836")


# --- Novo Código para Análise de Frequência Relativa por Estado ---

# Calcular a frequência relativa
depressao_v0001_relativa = (depressao_v0001 / depressao_v0001.sum()) * 100

plt.figure(figsize=(10, 8))
depressao_v0001_relativa.plot(kind='barh')
plt.title('Frequência Relativa de Casos de Depressão por Estado')
plt.xlabel('Frequência Relativa (%)')
plt.ylabel('Estado')
plt.grid(axis='x', linestyle='--')
plt.tight_layout()
plt.show()

# Top 5 estados com mais casos de depressão
top_5_depressao = depressao_v0001.sort_values(ascending=False).head(5)
print("\n--- Top 5 Estados com Maior Número de Casos de Depressão ---")
for state, count in top_5_depressao.items():
    print(f"- {state}: {count} casos")

# 5 estados com menos casos de depressão
bottom_5_depressao = depressao_v0001.head(5)
print("\n--- Top 5 Estados com Menor Número de Casos de Depressão ---")
for state, count in bottom_5_depressao.items():
    print(f"- {state}: {count} casos")

In [ ]:
# @title
# --- Novo Código para Análise por Região ---# Função para mapear o código do estado para a região
def map_region(state_code):
    if 10 <= state_code < 20:
        return 'Norte'
    elif 20 <= state_code < 30:
        return 'Nordeste'
    elif 30 <= state_code < 40:
        return 'Sudeste'
    elif 40 <= state_code < 50:
        return 'Sul'
    elif 50 <= state_code < 60:
        return 'Centro-Oeste'
    return 'Outros'

# Criar uma nova coluna 'region' no df_analise
df_analise['region'] = df_analise['V0001'].apply(map_region)

# Contar os casos de depressão por região
depressao_por_regiao = df_analise[df_analise['Q092'] == 1]['region'].value_counts().sort_values(ascending=False)

# Criar o gráfico de barras vertical
plt.figure(figsize=(10, 6))
depressao_por_regiao.plot(kind='bar')
plt.title('Distribuição de Casos de Depressão por Região')
plt.xlabel('Região')
plt.ylabel('Contagem')
plt.grid(axis='y', linestyle='--')
plt.xticks(rotation=45, ha='right') # Rotacionar os rótulos do eixo X para melhor visualização
plt.tight_layout()
plt.show()

print(f"Total de casos de depressão por região: {depressao_por_regiao.sum()}/836")

print("\nCasos de depressão por região:")
for region, count in depressao_por_regiao.items():
    print(f"- {region}: {count} casos")

## Analise exploratoria Nutricional

In [ ]:
# @title
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv(
    r"/content/drive/MyDrive/PNS2019/pns2019.csv",
    sep=",",
    low_memory=False
)

# Limpar nomes de colunas (evita erro escondido)
df.columns = df.columns.str.strip()

# ##########################################
#-----> AQUI EMBAIXO COLOCA O ATRIBUTO DA SUA DOENCA
##########################################
df = df.rename(columns={"Q092": "depressao"})


# Tirei o filtro de idade
# Pessoas com depressão
depressao = df.query("depressao == 1") # and C008 < 30 and C008 > 17")

# Pessoas sem nenhuma doença
sem_doenca = df.query(
    "Q00201 == 2 and Q03001 == 2 and Q060 == 2 and Q06306 == 2 and "
    "Q068 == 2 and Q074 == 2 and Q079 == 2 and Q088 == 2 and "
    "Q11604 == 2 and Q120 == 2 and Q124 == 2 and Q128 == 2 and "
    "depressao == 2 and Q084 == 2 and Q11006 == 2"
)

# Base final de análise, filtrada
df_analise = pd.concat([depressao, sem_doenca])






print("Categorias (dias por semana) Baixo: \n 0 a 2 dias \n Médio: 3 a 5 dias \n Alto: 6 a 7 dias")

# =========================
# 1. Lista de atributos de alimentos por semana
# =========================
atributos = [
    'P006', 'P00901', 'P01101', 'P013', 'P015',
    'P01601', 'P018', 'P02001', 'P02002',
    'P023', 'P02501', 'P02602', 'P02801'
]

# =========================
# 1.1 Nome legível dos atributos
# =========================
nomes = {
    'P006': 'Feijão',
    'P00901': 'Verduras/Legumes',
    'P01101': 'Carne Vermelha',
    'P013': 'Frango',
    'P015': 'Peixe',
    'P01601': 'Suco Natural',
    'P018': 'Frutas',
    'P02001': 'Suco Industrializado',
    'P02002': 'Refrigerante',
    'P023': 'Leite',
    'P02501': 'Doces',
    'P02602': 'Substituição de Refeição',
    'P02801': 'Álcool'
}

# =========================
# 2. Criar variável de doença
# =========================
df_analise['doenca'] = df_analise['depressao'].apply(lambda x: 1 if x == 1 else 0) #se for 1, tem a doença, de resto considera q nn tem

# =========================
# 3. Loop
# =========================
resultados = {}

for atributo in atributos:

    df_temp = df_analise[[atributo, 'doenca']].copy()

    # Remover valores inválidos
    df_temp = df_temp[df_temp[atributo] != 9]

    # Criar categorias
    df_temp[atributo + '_cat'] = pd.cut(
        df_temp[atributo],
        bins=[-1, 2, 5, 7],
        labels=['Baixo', 'Médio', 'Alto']
    )

    # Tabela, aqui calcula a P(doenc​a∣categoria)
    tabela = pd.crosstab(
        df_temp[atributo + '_cat'],
        df_temp['doenca'],
        normalize='index'
    )

    resultados[atributo] = tabela

    if 1 in tabela.columns:
        prob_doenca = tabela[1]

        nome_legivel = nomes.get(atributo, atributo)

        # Gráfico
        plt.figure()
        prob_doenca.plot(kind='bar')
        plt.title(f'Probabilidade de doença vs {nome_legivel}')
        plt.xlabel('Consumo')
        plt.ylabel('Probabilidade de doença')
        plt.xticks(rotation=0)
        plt.show()

        # Print bonito
        print(f"\n=== {nome_legivel} ({atributo}) ===")
        print(prob_doenca)

# import matplotlib.pyplot as plt

prob_doenca.plot(kind='bar')
plt.title('Probabilidade de doença por consumo de refrigerante')
plt.xlabel('Consumo de refri')
plt.ylabel('Probabilidade de doença')
plt.show()

#-------- AQUI FAZ O RANKING

ranking = []

for atributo, tabela in resultados.items():
    if 1 in tabela.columns:

        # Garantir que todas categorias existem
        if all(cat in tabela.index for cat in ['Baixo', 'Médio', 'Alto']):

            baixo = tabela.loc['Baixo', 1]
            alto = tabela.loc['Alto', 1]

            impacto = alto - baixo

            nome_legivel = nomes.get(atributo, atributo)

            ranking.append((nome_legivel, atributo, impacto))

# Ordenar do maior impacto pro menor
ranking = sorted(ranking, key=lambda x: x[2], reverse=True)

# Print bonito
print("\n=== Ranking de impacto (Alto - Baixo) ===\n")

for nome, cod, impacto in ranking:
    print(f"{nome} ({cod}) → {impacto:.4f}")

In [ ]:
# @title


print("Categorias (dias por semana) Baixo: 0 a 2 dias \n Médio: 3 a 5 dias \n Alto: 6 a 7 dias")
print("")
# =========================
# 1. Lista de atributos
# =========================
atributos = [
    'P006', 'P00901', 'P01101', 'P013', 'P015',
    'P01601', 'P018', 'P02001', 'P02002',
    'P023', 'P02501', 'P02602', 'P02801'
]

# =========================
# 1.1 Nome legível dos atributos
# =========================
nomes = {
    'P006': 'Feijão',
    'P00901': 'Verduras/Legumes',
    'P01101': 'Carne Vermelha',
    'P013': 'Frango',
    'P015': 'Peixe',
    'P01601': 'Suco Natural',
    'P018': 'Frutas',
    'P02001': 'Suco Industrializado',
    'P02002': 'Refrigerante',
    'P023': 'Leite',
    'P02501': 'Doces',
    'P02602': 'Substituição de Refeição',
    'P02801': 'Álcool'
}

# =========================
# 2. Criar variável de doença
# =========================
df_analise['doenca'] = df_analise['depressao'].apply(lambda x: 1 if x == 1 else 0)

# =========================
# 3. Loop
# =========================
resultados = {}

for atributo in atributos:

    df_temp = df_analise[[atributo, 'doenca']].copy()

    # Remover valores inválidos
    df_temp = df_temp[df_temp[atributo] != 9]

    # Criar categorias
    df_temp[atributo + '_cat'] = pd.cut(
        df_temp[atributo],
        bins=[-1, 2, 5, 7],
        labels=['Baixo', 'Médio', 'Alto']
    )

    # Tabela
    tabela = pd.crosstab(
        df_temp[atributo + '_cat'],
        df_temp['doenca'],
        normalize='index'
    )

    resultados[atributo] = tabela

    if 1 in tabela.columns:
        prob_doenca = tabela[1]

        nome_legivel = nomes.get(atributo, atributo)

        # Gráfico
        plt.figure()
        prob_doenca.plot(kind='bar')
        plt.title(f'Probabilidade de doença vs {nome_legivel}')
        plt.xlabel('Consumo')
        plt.ylabel('Probabilidade de doença')
        plt.xticks(rotation=0)
        plt.show()

        # Print bonito
        print(f"\n=== {nome_legivel} ({atributo}) ===")
        print(prob_doenca)

# import matplotlib.pyplot as plt

prob_doenca.plot(kind='bar')
plt.title('Probabilidade de doença por consumo de refrigerante')
plt.xlabel('Consumo de refri')
plt.ylabel('Probabilidade de doença')
plt.show()

In [ ]:
# @title
ranking = []

for atributo, tabela in resultados.items():
    if 1 in tabela.columns:

        # Garantir que todas categorias existem
        if all(cat in tabela.index for cat in ['Baixo', 'Médio', 'Alto']):

            baixo = tabela.loc['Baixo', 1]
            alto = tabela.loc['Alto', 1]

            impacto = alto - baixo

            nome_legivel = nomes.get(atributo, atributo)

            ranking.append((nome_legivel, atributo, impacto))

# Ordenar do maior impacto pro menor
ranking = sorted(ranking, key=lambda x: x[2], reverse=True)

# Print bonito
print("\n=== Ranking de impacto (Alto - Baixo) ===\n")

for nome, cod, impacto in ranking:
    print(f"{nome} ({cod}) → {impacto:.4f}")

# Seleção de atributos

In [47]:
df = df_analise = pd.read_csv(
    r"/content/drive/MyDrive/PNS2019/df_analise.csv",
    sep=",",
    low_memory=False
)

Lista de variaveis

In [ ]:

# =========================
# 1. DICIONÁRIO (SEU MAPEAMENTO)
# =========================

info_variaveis = {
    # Tabaco
    'P050': ('Qualitativo','Nominal'),
    'P051': ('Qualitativo','Nominal'),
    'P052': ('Qualitativo','Ordinal'),
    'P06701': ('Qualitativo','Ordinal'),

    # Sono
    'N010': ('Qualitativo','Ordinal'),
    'Q132': ('Qualitativo','Nominal'),
    'Q133': ('Quantitativo','Discreto'),
    'H024': ('Qualitativo','Ordinal'),

    # Telas
    'P04501': ('Qualitativo','Ordinal'),
    'P04502': ('Qualitativo','Ordinal'),
    'A018011': ('Qualitativo','Nominal'),
    'A018023': ('Qualitativo','Nominal'),
    'A01901': ('Qualitativo','Nominal'),

    # Atividade física
    'P034': ('Qualitativo','Nominal'),
    'P035': ('Quantitativo','Discreto'),
    'P036': ('Qualitativo','Nominal'),
    'P03701': ('Quantitativo','Discreto'),
    'P03702': ('Quantitativo','Discreto'),
    'P04701': ('Qualitativo','Nominal'),
    'P04801': ('Qualitativo','Nominal'),

    # Socioeconômico
    'VDF002': ('Quantitativo','Contínuo'),
    'VDF003': ('Quantitativo','Contínuo'),
    'VDF004': ('Qualitativo','Ordinal'),
    'VDD004A': ('Qualitativo','Ordinal'),
    'D00901': ('Qualitativo','Ordinal'),
    'A001': ('Qualitativo','Nominal'),
    'A01001': ('Quantitativo','Discreto'),
    'C004': ('Qualitativo','Nominal'),
    'C01001': ('Qualitativo','Nominal'),

    # Social
    'M01401': ('Quantitativo','Discreto'),
    'M01501': ('Quantitativo','Discreto'),
    'M01901': ('Qualitativo','Ordinal'),
    'C009': ('Qualitativo','Nominal'),
    'VDC001': ('Quantitativo','Discreto'),

    # Eventos psicológicos
    'V003': ('Qualitativo','Ordinal'),
    'V015': ('Qualitativo','Ordinal'),
    'V03502': ('Qualitativo','Nominal'),
    'N017': ('Qualitativo','Ordinal'),
    'E008': ('Qualitativo','Nominal'),

    # Alimentação
    'P01101': ('Quantitativo','Discreto'),
    'P015': ('Quantitativo','Discreto'),
    'P018': ('Quantitativo','Discreto'),
    'S136': ('Qualitativo','Nominal'),

    # Individuais
    'C008': ('Quantitativo','Discreto'),
    'C006': ('Qualitativo','Nominal'),
    'P00104': ('Quantitativo','Contínuo'),
    'P00404': ('Quantitativo','Discreto'),
    'W00103': ('Quantitativo','Contínuo'),
    'W00203': ('Quantitativo','Contínuo'),

    # Álcool
    'P027': ('Qualitativo','Ordinal'),
    'P02801': ('Quantitativo','Discreto'),
    'P029': ('Quantitativo','Discreto'),
    'P03201': ('Qualitativo','Nominal'),
    'P03202': ('Quantitativo','Discreto'),

    # Açúcar
    'P02501': ('Quantitativo','Discreto'),
    'P02001': ('Quantitativo','Discreto'),
    'P02101': ('Qualitativo','Nominal'),
    'P02002': ('Quantitativo','Discreto'),
    'P02102': ('Qualitativo','Nominal'),

    # Hábitos
    'P01001': ('Qualitativo','Ordinal'),
    'P019': ('Qualitativo','Ordinal'),

    # Crônicas
    'J007': ('Qualitativo','Nominal'),
    'J00402': ('Qualitativo','Nominal'),
    'Q128': ('Qualitativo','Nominal'),

    # Drogas
    'J02702': ('Qualitativo','Nominal')
}

# =========================
# 2. VARIÁVEIS EM INTERVALO
# =========================

# Tabaco
p054_freq = [f'P054{str(i).zfill(2)}' for i in range(1,20)]
for v in p054_freq:
    info_variaveis[v] = ('Qualitativo','Ordinal')

p054_qtd = [f'P054{str(i).zfill(2)}' for i in range(2,22)]
for v in p054_qtd:
    info_variaveis[v] = ('Quantitativo','Discreto')

# Eventos psicológicos
for i in range(1,6):
    info_variaveis[f'V0020{i}'] = ('Qualitativo','Nominal')
    info_variaveis[f'V0140{i}'] = ('Qualitativo','Nominal')

# Alimentação
for i in range(0,20):
    info_variaveis[f'P006{str(i).zfill(2)}'] = ('Qualitativo','Nominal')

# =========================
# 3. FILTRAR EXISTENTES
# =========================
variaveis = [v for v in info_variaveis if v in df_analise.columns]

# =========================
# 4. FUNÇÃO DE RESUMO
# =========================
def resumo(col):
    s = df_analise[col]

    tipo, natureza = info_variaveis[col]

    return {
        "variavel": col,
        "tipo": tipo,
        "natureza": natureza,
        "media": s.mean() if tipo == "Quantitativo" else np.nan,
        "mediana": s.median() if tipo == "Quantitativo" else np.nan,
        "desvio_padrao": s.std() if tipo == "Quantitativo" else np.nan,
        "min": s.min() if tipo == "Quantitativo" else np.nan,
        "max": s.max() if tipo == "Quantitativo" else np.nan,
        "moda": s.mode().iloc[0] if not s.mode().empty else np.nan,
        "valores_unicos": s.nunique(),
        "missing_%": s.isnull().mean()*100
    }

# =========================
# 5. TABELA FINAL
# =========================
tabela = pd.DataFrame([resumo(v) for v in variaveis])

tabela = tabela.round(2)

print(tabela)

# salvar
tabela.to_csv("tabela_descritiva_final.csv", index=False)

In [ ]:
# =========================
# 2. LISTAS DE VARIÁVEIS
# =========================

# Qualitativas (nominal + ordinal)
cat_vars = [
    'P050','P051','P052','P06701','Q132','H024',
    'P04501','P04502','A018011','A018023','A01901',
    'P034','P036','P04701','P04801',
    'VDF004','VDD004A','D00901','A001','C004','C01001',
    'M01901','C009',
    'V003','V015','N017',
    'P006','P00601','P00602','P00603','P00604','P00605',
    #'P00606',
    'P00607','P00608','P00609','P00610','P00611','P00612','P00613',
    'S136','C006','P027','P03201',
    'P02101','P02102',
    'P01001','P019',
    'J007','J00402','Q128','J02702'
]

# Quantitativas discretas
disc_vars = [
    'P05402','P05403','P05404','P05405','P05406','P05407','P05408','P05409',
    'P05410','P05411','P05412','P05413','P05414','P05415','P05416','P05417',
    'P05418','P05419','P05420','P05421',
    'Q133','P035','P03701','P03702',
    'A01001','M01401','M01501','VDC001',
    'P01101','P015','P018',
    'P02801','P029','P03202',
    'P02501','P02001','P02002',
    'P02602','C008'
]

# Quantitativas contínuas
cont_vars = [
    'VDF002','VDF003',
    'P00104','W00103','W00203'
]

# =========================
# 3. VISÃO GERAL
# =========================
print("Shape:", df.shape)
print(df_analise.info())

# =========================
# 4. MISSING VALUES
# =========================
missing = df_analise.isnull().mean()*100
print("\nMissing (%):")
print(missing.sort_values(ascending=False))

# =========================
# 5. ANÁLISE NUMÉRICA
# =========================
num_vars = disc_vars + cont_vars

print("\nResumo Numérico:")
num_vars = [v for v in (disc_vars + cont_vars) if v in df_analise.columns]

print(df_analise[num_vars].describe())

# =========================
# 6. ANÁLISE CATEGÓRICA
# =========================
for col in cat_vars:
    print(f"\n===== {col} =====")
    print(df_analise[col].value_counts(dropna=False))
    print(df_analise[col].value_counts(normalize=True, dropna=False)*100)

# =========================
# 7. OUTLIERS (IQR)
# =========================
for col in num_vars:
    Q1 = df_analise[col].quantile(0.25)
    Q3 = df_analise[col].quantile(0.75)
    IQR = Q3 - Q1

    outliers = df_analise[(df_analise[col] < Q1 - 1.5*IQR) | (df_analise[col] > Q3 + 1.5*IQR)]

    print(f"{col}: {len(outliers)} outliers")

# =========================
# 8. CORRELAÇÃO
# =========================
corr = df_analise[num_vars].corr()
print("\nCorrelação:")
print(corr)

# =========================
# 9. AGRUPAMENTO (EXEMPLO)
# =========================
# Exemplo: se tiver variável de depressão
# df.groupby('depressao')['C008'].mean()

Conjunto de variaveis antigo

In [27]:
# cat_vars = [
#     'P050','P051','P052','P06701','Q132','H024',
#     'P04501','P04502','A018011','A018023','A01901',
#     'P034','P036','P04701','P04801',
#     'VDF004','VDD004A','D00901','A001','C004','C01001',
#     'M01901','C009',
#     'V003','V015','N017',
#     'P006','P00601','P00602','P00603','P00604','P00605',
#     'V0015',
#     'P00607','P00608','P00609','P00610','P00611','P00612','P00613',
#     'S136','C006','P027','P03201',
#     'P02101','P02102',
#     'P01001','P019',
#     'J007','J00402','Q128','J02702'
# ]
## 51 colunas

Cojunto de variaveis atualizado

In [42]:
cat_vars = [
    # --- Controle e Identificação ---
    'V0001', 'V0026', 'V0015',

    # --- Diagnóstico e Gravidade (Variáveis Alvo/Consequência) ---
    'Q092', 'Q09201', 'Q09202', 'Q109',

    # --- Sintomas PHQ-9 (Consequências Psicológicas Diretas) ---
    'N010', 'N011', 'N012', 'N013', 'N014', 'N015', 'N016', 'N017', 'N018',

    # --- Saúde Geral, Sono e Libido (Marcadores de Sintomas) ---
    'J00101', 'J002', 'Q132', 'H024', 'Y002',

    # --- Comorbidades Crônicas (Causas/Consequências Biológicas) ---
    'J007', 'Q00201', 'Q03001', 'Q06306', 'J00402', 'Q128', 'J02702',

    # --- Comportamento e Estilo de Vida (Fatores Modificáveis) ---
    'P050', 'P051', 'P052', 'P06701', # Tabaco/Nicotina
    'P027', 'P03201',                 # Álcool
    'P04501', 'P04502',               # Uso de Telas
    'P034', 'P036', 'P04701', 'P04801', # Atividade Física

    # --- Alimentação e Nutrição (Causas e Padrões) ---
    'P006', 'P00601', 'P00602', 'P00603', 'P00604', 'P00605',
    'P00607', 'P00608', 'P00609', 'P00610', 'P00611', 'P00612', 'P00613',
    'P00614', 'P00615', 'P00616', 'P00617', 'P00618', 'P00619', # Ultraprocessados
    'P00620', 'P00621', 'P00622', 'P00623',                     # Embutidos/Processados
    'P02602', 'P02101', 'P02102', 'P01001', 'P019', 'S136',     # Hábitos/Suplementos

    # --- Fatores Sociais e Violência (Gatilhos e Apoio) ---
    'M01401', 'M01501', 'M01901',     # Rede de Apoio e Religiosidade
    'V00201', 'V00202', 'V00203', 'V00204', 'V00205', # Tipos de Violência
    'V003', 'V015', 'V03502',         # Frequência e Consequência Psicológica

    # --- Demografia e Socioeconomia (Determinantes Sociais) ---
    'VDF004', 'VDD004A', 'D00901', 'VDE014', # Renda, Educação e Setor de Trabalho
    'A001', 'C004', 'C01001', 'C011',       # Moradia e Estado Civil
    'C006', 'C008', 'C009', #'Y008',
    'VDC001' # Sexo, Idade, Raça, Orientação e Domicílio
]
# 92 a 93 colunas

In [43]:
df_filtrado = df_analise[cat_vars]
df_filtrado.head()

,V0001,V0026,V0015,Q092,Q09201,Q09202,Q109,N010,N011,N012,...,D00901,VDE014,A001,C004,C01001,C011,C006,C008,C009,VDC001
0,11,1,1,1.0,1.0,3.0,1.0,3.0,3.0,2.0,...,10.0,NaN,1.0,1.0,1.0,4.0,2.0,29.0,1.0,3.0
1,11,1,1,1.0,2.0,3.0,1.0,1.0,1.0,1.0,...,NaN,7.0,2.0,14.0,2.0,4.0,2.0,22.0,4.0,2.0
2,11,1,1,1.0,2.0,3.0,1.0,1.0,1.0,1.0,...,NaN,7.0,1.0,5.0,2.0,4.0,1.0,24.0,1.0,2.0
3,11,1,1,1.0,1.0,3.0,2.0,1.0,2.0,2.0,...,NaN,NaN,1.0,1.0,1.0,4.0,2.0,24.0,1.0,4.0
4,11,1,1,1.0,1.0,3.0,1.0,2.0,1.0,1.0,...,NaN,NaN,1.0,5.0,1.0,4.0,1.0,22.0,4.0,4.0

In [44]:
# Mapeamento de variáveis categóricas PNS 2019
pns_mapping = {
    # --- Controle e Identificação ---
    'V0001': 'V0001 - Unidade da Federação',
    'V0026': 'V0026 - Tipo de situação censitária',
    'V0015': 'V0015 - Tipo da entrevista',

    # --- Diagnóstico e Gravidade (Variáveis Alvo/Consequência) ---
    'Q092': 'Q092 - Algum médico ou profissional de saúde mental já lhe deu o diagnóstico de depressão?',
    'Q09201': 'Q09201 - Algum médico já lhe receitou algum medicamento para depressão?',
    'Q09202': 'Q09202 - Nas duas últimas semanas o(a) senhor(a) usou algum medicamento para depressão?',
    'Q109': 'Q109 - Grau em que a depressão limita as suas atividades habituais',

    # --- Sintomas PHQ-9 (Consequências Psicológicas Diretas) ---
    'N010': 'N010 - Frequência de problemas no sono nas últimas duas semanas',
    'N011': 'N011 - Frequência de problemas por não se sentir descansado ou disposto',
    'N012': 'N012 - Frequência de pouco interesse ou prazer em fazer as coisas',
    'N013': 'N013 - Frequência de problemas para se concentrar nas atividades habituais',
    'N014': 'N014 - Frequência de problemas na alimentação (falta de apetite ou comer muito)',
    'N015': 'N015 - Frequência de lentidão para se movimentar ou agitação/inquietude',
    'N016': 'N016 - Frequência de sentimento de depressão ou falta de perspectiva',
    'N017': 'N017 - Frequência de sentimento de fracasso ou ter decepcionado a família',
    'N018': 'N018 - Frequência de pensamentos de se ferir ou de que seria melhor estar morto',

    # --- Saúde Geral, Sono e Libido (Marcadores de Sintomas) ---
    'J00101': 'J00101 - Percepção do estado de saúde (bem-estar físico e mental)',
    'J002': 'J002 - Deixou de realizar atividades habituais por motivo de saúde (2 semanas)',
    'Q132': 'Q132 - Uso de algum medicamento para dormir nas últimas duas semanas',
    'H024': 'H024 - Orientações sobre alimentação saudável, boa higiene e sono adequado',
    'Y002': 'Y002 - Teve relações sexuais nos últimos doze meses',

    # --- Comorbidades Crônicas (Causas/Consequências Biológicas) ---
    'J007': 'J007 - Algum médico já deu o diagnóstico de alguma doença crônica',
    'Q00201': 'Q00201 - Algum médico já lhe deu o diagnóstico de hipertensão arterial',
    'Q03001': 'Q03001 - Algum médico já lhe deu o diagnóstico de diabetes',
    'Q06306': 'Q06306 - Algum médico já lhe deu o diagnóstico de uma doença do coração',
    'J00402': 'J00402 - Principal motivo de saúde que impediu atividades habituais',
    'Q128': 'Q128 - Algum médico já lhe deu diagnóstico de outra doença crônica',
    'J02702': 'J02702 - Qual foi o principal atendimento de saúde que recebeu',

    # --- Comportamento e Estilo de Vida (Fatores Modificáveis) ---
    'P050': 'P050 - Atualmente fuma algum produto do tabaco',
    'P051': 'P051 - No passado fumou algum produto do tabaco diariamente',
    'P052': 'P052 - No passado fumou algum produto do tabaco (diário ou menos)',
    'P06701': 'P06701 - Uso de aparelhos eletrônicos com nicotina líquida ou folha de tabaco',
    'P027': 'P027 - Frequência com que costuma consumir alguma bebida alcoólica',
    'P03201': 'P03201 - Consumo de cinco ou mais doses de álcool em uma única ocasião (30 dias)',
    'P04501': 'P04501 - Horas diárias que costuma ficar assistindo televisão',
    'P04502': 'P04502 - Horas diárias de uso de computador, tablet ou celular para lazer',
    'P034': 'P034 - Prática de algum tipo de exercício físico ou esporte nos últimos 3 meses',
    'P036': 'P036 - Principal exercício físico ou esporte que pratica com mais frequência',
    'P04701': 'P04701 - Conhece algum programa público de estímulo à atividade física',
    'P04801': 'P04801 - Participa de algum programa público de estímulo à atividade física',

    # --- Alimentação e Nutrição (Causas e Padrões) ---
    'P006': 'P006 - Quantos dias na semana costuma comer feijão',
    'P00601': 'P00601 - Comeu arroz, macarrão, polenta, cuscuz ou milho verde ontem',
    'P00602': 'P00602 - Comeu batata comum, mandioca, cará ou inhame ontem',
    'P00603': 'P00603 - Comeu feijão, ervilha, lentilha ou grão de bico ontem',
    'P00604': 'P00604 - Comeu carne de boi, porco, frango ou peixe ontem',
    'P00605': 'P00605 - Comeu ovo ontem',
    'P00607': 'P00607 - Comeu alface, couve, brócolis, agrião ou espinafre ontem',
    'P00608': 'P00608 - Comeu abóbora, cenoura, batata doce ou quiabo ontem',
    'P00609': 'P00609 - Comeu tomate, pepino, abobrinha, berinjela, chuchu ou beterraba ontem',
    'P00610': 'P00610 - Comeu mamão, manga, melão amarelo ou pequi ontem',
    'P00611': 'P00611 - Comeu laranja, banana, maçã ou abacaxi ontem',
    'P00612': 'P00612 - Tomou leite ontem',
    'P00613': 'P00613 - Comeu amendoim, castanha de caju ou castanha do Brasil ontem',
    'P00614': 'P00614 - Tomou refrigerante ontem',
    'P00615': 'P00615 - Tomou suco de caixinha, lata ou refresco em pó ontem',
    'P00616': 'P00616 - Tomou bebida achocolatada ou iogurte com sabor ontem',
    'P00617': 'P00617 - Comeu salgadinho de pacote ou biscoito salgado ontem',
    'P00618': 'P00618 - Comeu biscoito doce ou bolo de pacote ontem',
    'P00619': 'P00619 - Comeu sorvete, chocolate ou sobremesa industrializada ontem',
    'P00620': 'P00620 - Comeu salsicha, linguiça, mortadela ou presunto ontem',
    'P00621': 'P00621 - Comeu pão de forma, de cachorro-quente ou de hambúrguer ontem',
    'P00622': 'P00622 - Comeu margarina, maionese, ketchup ou molhos industrializados ontem',
    'P00623': 'P00623 - Comeu macarrão instantâneo ou prato congelado industrializado ontem',
    'P02602': 'P02602 - Dias na semana que substitui o almoço por lanches rápidos',
    'P02101': 'P02101 - Tipo de suco de caixinha ou refresco em pó que costuma tomar',
    'P02102': 'P02102 - Tipo de refrigerante que costuma tomar',
    'P01001': 'P01001 - Frequência diária de consumo de verduras ou legumes',
    'P019': 'P019 - Quantas vezes por dia costuma comer frutas',
    'S136': 'S136 - Tomou ferro com vitaminas nos primeiros três meses após o parto',

    # --- Fatores Sociais e Violência (Gatilhos e Apoio) ---
    'M01401': 'M01401 - Quantos familiares ou parentes pode contar em momentos bons ou ruins',
    'M01501': 'M01501 - Quantos amigos próximos pode contar em momentos bons ou ruins',
    'M01901': 'M01901 - Frequência de atividades religiosas coletivas nos últimos 12 meses',
    'V00201': 'V00201 - Violência: Alguém te ofendeu, humilhou ou ridicularizou (12 meses)',
    'V00202': 'V00202 - Violência: Alguém gritou com você ou te xingou (12 meses)',
    'V00203': 'V00203 - Violência: Uso de redes sociais/celular para ameaçar ou expor imagens (12 meses)',
    'V00204': 'V00204 - Violência: Alguém te ameaçou de ferir alguém importante (12 meses)',
    'V00205': 'V00205 - Violência: Alguém destruiu alguma coisa sua de propósito (12 meses)',
    'V003': 'V003 - Frequência da violência psicológica sofrida nos últimos 12 meses',
    'V015': 'V015 - Frequência da violência física sofrida nos últimos doze meses',
    'V03502': 'V03502 - Consequência psicológica da violência (medo, tristeza, depressão)',

    # --- Demografia e Socioeconomia (Determinantes Sociais) ---
    'VDF004': 'VDF004 - Faixa de rendimento domiciliar per capita',
    'VDD004A': 'VDD004A - Nível de instrução mais elevado alcançado (padronizado)',
    'D00901': 'D00901 - Curso mais elevado que frequentou anteriormente',
    'VDE014': 'VDE014 - Grupamentos de atividade do trabalho principal',
    'A001': 'A001 - Tipo do domicílio',
    'C004': 'C004 - Condição no domicílio (responsável, cônjuge, filho, etc)',
    'C01001': 'C01001 - Cônjuge ou companheiro(a) mora em nesse domicílio',
    'C011': 'C011 - Estado civil do morador',
    'C006': 'C006 - Sexo do morador',
    'C008': 'C008 - Idade do morador na data de referência',
    'C009': 'C009 - Cor ou raça do morador',
    'VDC001': 'VDC001 - Número de componentes do domicílio'
}

# Para renomear o dataframe final:
# df.rename(columns=pns_mapping, inplace=True)

In [46]:
df_filtrado.rename(columns=pns_mapping, inplace=True)
df_filtrado.head()

/tmp/ipykernel_77399/2948382600.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado.rename(columns=pns_mapping, inplace=True)

,V0001 - Unidade da Federação,V0026 - Tipo de situação censitária,V0015 - Tipo da entrevista,Q092 - Algum médico ou profissional de saúde mental já lhe deu o diagnóstico de depressão?,Q09201 - Algum médico já lhe receitou algum medicamento para depressão?,Q09202 - Nas duas últimas semanas o(a) senhor(a) usou algum medicamento para depressão?,Q109 - Grau em que a depressão limita as suas atividades habituais,N010 - Frequência de problemas no sono nas últimas duas semanas,N011 - Frequência de problemas por não se sentir descansado ou disposto,N012 - Frequência de pouco interesse ou prazer em fazer as coisas,...,D00901 - Curso mais elevado que frequentou anteriormente,VDE014 - Grupamentos de atividade do trabalho principal,A001 - Tipo do domicílio,"C004 - Condição no domicílio (responsável, cônjuge, filho, etc)",C01001 - Cônjuge ou companheiro(a) mora em nesse domicílio,C011 - Estado civil do morador,C006 - Sexo do morador,C008 - Idade do morador na data de referência,C009 - Cor ou raça do morador,VDC001 - Número de componentes do domicílio
0,11,1,1,1.0,1.0,3.0,1.0,3.0,3.0,2.0,...,10.0,NaN,1.0,1.0,1.0,4.0,2.0,29.0,1.0,3.0
1,11,1,1,1.0,2.0,3.0,1.0,1.0,1.0,1.0,...,NaN,7.0,2.0,14.0,2.0,4.0,2.0,22.0,4.0,2.0
2,11,1,1,1.0,2.0,3.0,1.0,1.0,1.0,1.0,...,NaN,7.0,1.0,5.0,2.0,4.0,1.0,24.0,1.0,2.0
3,11,1,1,1.0,1.0,3.0,2.0,1.0,2.0,2.0,...,NaN,NaN,1.0,1.0,1.0,4.0,2.0,24.0,1.0,4.0
4,11,1,1,1.0,1.0,3.0,1.0,2.0,1.0,1.0,...,NaN,NaN,1.0,5.0,1.0,4.0,1.0,22.0,4.0,4.0

In [51]:
# Base final de análise
df_filtrado.to_csv("/content/drive/MyDrive/PNS2019/df_analise02.csv", index=False)